name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test build
        run: npm run build

  verify:
    name: Verify
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify application documentation
        run: echo "Verifying application documentation"

      - name: Check version file
        run: cat VERSION

  security_verify:
    name: Security Verify
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run security checks
        run: npm audit

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: security_verify
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Set up Podman
        run: sudo apt-get install podman -y  # Install Podman

      - name: Build Docker image using Podman
        run: podman build -t udaykumar7697/h5-news-app-web:latest .

  upload:
    name: Upload
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a secret


      - name: Push Docker image
        run: |
         docker push udaykumar7697/h5-news-app-web:latest  # Replace with your Docker Hub username

  trigger_pipeline:
    name: Trigger CD Pipeline
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger CD pipeline
        run: echo "Triggering CD pipeline"
